### ISSUE TITLE
Pull case info into Twilio SMS flow

### ISSUE THREAD

**Issue by bbrewington** [codeforatlanta/georgia-courtbot#13]
Given text from user, make API call from Twilio to <Cloud Provider> to determine if case is found:

```
Given:
    UserText
Retrieve:
    CaseNumber
```

Given a case number, make API call from Twilio to <Cloud Provider> to get case information:

```
Given:
    CaseNumber
Retrieve:
    HearingDate
    HearingTime
    CourtRoom
```

**Comment by BennyJW** [comment]
I can take this issue on.

**Comment by bbrewington** [comment]
Calling this done - we can continue iterating on it, but the initial need is met w/ above PR & configuration from hack night last night
